name: Frontend CI/CD Pipeline
on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    ci:
        name: Lint and Build Check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                    node-version: '20'
                    cache: 'npm' 
            - name: Install dependencies
              run: npm install
              
            - name: Run ESLint
              run: npm run lint
            
            - name: TypeScript type check
              run: npx tsc --noEmit
            
            - name: Run frontend tests
              run: npm test

            - name: Build project
              run: npm run build
            
            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist-build               
                path: dist/                    
                retention-days: 1